import { Inter } from "next/font/google";
import ClientWrapper from './ClientWrapper';
import 'tailwindcss/tailwind.css';
import './globals.css';
import { GoogleTagManager } from '@next/third-parties/google'
import Header from "./components/Header";
import Footer from "./components/Footer";

// import { GoogleTagManager } from '@next/third-parties/google'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "R3 Suprimentos",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="pt-BR">
      <head>
        <GoogleTagManager gtmId="GTM-P6NMRBD"></GoogleTagManager>
      </head>
      <body className={inter.className}>
        <Header />
        <GoogleTagManager gtmId="GTM-P6NMRBD"></GoogleTagManager>
        <ClientWrapper>
          {children}
        </ClientWrapper>
        <Footer />
      </body>
    </html>
  );
};

export default RootLayout;

